/* DEFAULT REDUCER */
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW'

/* SETTINGS REDUCER */
export const TOGGLE_THEME = 'TOGGLE_THEME'
export const SET_LANG = 'SET_LANG'
export const SET_START_VIEW = 'SET_START_VIEW'
export const SET_LIMIT_PER_PRODUCT = 'SET_LIMIT_PER_PRODUCT'
export const SET_OPEN_LINK_ANSWER_IN = 'SET_OPEN_LINK_ANSWER_IN'
