/* DEFAULT REDUCER */
export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_THREAD_VIEWED = 'ADD_THREAD_VIEWED'

/* ANSWERS REDUCER */
export const SET_IS_SEARCHING = 'SET_IS_SEARCHING'
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'
export const RESET_ANSWERS = 'RESET_ANSWERS'
export const SET_ANSWERS = 'SET_ANSWERS'
export const SHOW_MORE = 'SHOW_MORE'

/* SETTINGS REDUCER */
export const TOGGLE_THEME = 'TOGGLE_THEME'
export const SET_LANG = 'SET_LANG'
export const SET_START_VIEW = 'SET_START_VIEW'
export const SET_LIMIT_PER_PRODUCT = 'SET_LIMIT_PER_PRODUCT'
export const SET_OPEN_LINK_ANSWER_IN = 'SET_OPEN_LINK_ANSWER_IN'
export const SET_PRODUCTS_ID_SELECTED = 'SET_PRODUCTS_ID_SELECTED'
